# Generated by Django 3.1.7 on 2021-03-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='공개'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
